on: 
    release:
        types: [published,edited]
name: Build Release
jobs:
    release-linux-amd64:
        name: release linux/amd64
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.14.x
        - name: compile and release
          run: |
            RELEASE_VERSION=$(cat $EVENT_DATA | jq -r .release.tag_name)
            make darwin
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}